
apiVersion: v1
kind: Service
metadata:
  name: data-processing-service
spec:
  type: NodePort
  selector:
    app: data-processing-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30002
